# Ce fichier contient les properties utilisées pour les tests avec puppeteer

# Server
server.port: 8443
spring.main.lazy-initialization: false
cas.server.name: https://localhost:8443
cas.server.prefix: https://localhost:8443/cas

# Monitoring endpoints
management.endpoints.web.discovery.enabled: true
cas.monitor.endpoints.endpoint.defaults.access: ANONYMOUS
management.health.redis.enabled: true
management.health.redisHealthIndicator.enabled: true
management.endpoints.web.exposure.include: health,ssoSessions,ticketRegistry
management.endpoint.health.show-details: always
management.endpoints.enabled-by-default: true

# Audit
cas.audit.engine.enabled: true
cas.audit.slf4j.use-single-line: true
cas.audit.redis.host: localhost
cas.audit.redis.port: 6379

# Crypto
# In-Memory
cas.ticket.registry.in-memory.crypto.enabled: true
cas.ticket.registry.in-memory.crypto.signing.key: KncZu0oilh3gi0rMh85Xf477cc8OeIpL-uQ7dS6342PKENv3kWXFz5yu85n7pZIgNn8XLEAajMBqduuDWArzJQ
cas.ticket.registry.in-memory.crypto.encryption.key: 6Tcf5QqY9PmyZG7vY0PMiQ
# Ticket Registry
cas.tgc.crypto.enabled: true
cas.tgc.crypto.encryption.key: j3EISDyWRQ0tH8uzrl-M1DyoNvPHs9ipHFWRvWp-B2fStey9XZOuyTAZJ9OEdY4uR3bGJLX7SrBjrEBWJL9xXA
cas.tgc.crypto.signing.key: BV-wvTQ4e5-f7vyKfw3K2OG6haonkVBVNsCgC8YEQHAcDj2nPcAvtS3_WaP4QVm8GP0Tdd-geuPa8tNE-IcOdw
# Webflow
cas.webflow.crypto.enabled: true
cas.webflow.crypto.encryption.key: tEYwAdEdYSZGMA1gLqugKA
cas.webflow.crypto.signing.key: chz7ZTpcBIFdkZ-DLxjOYD-2OFj2B9xdDsAw5IGDsdsRi7_dfzo_EHEP9MyrVuVmxSeo3VHZBQSNmc6sjStiQQ
# Interrupt
cas.interrupt.cookie.crypto.enabled: true
cas.interrupt.cookie.crypto.encryption.key: Zw6N5Bs0vOQKxON6rb52hr5X6h9zi-BJeOs7oS1nQSk
cas.interrupt.cookie.crypto.signing.key: Yf1GaNfRqKzezShY3Jr0SfP_UVxaIkegsLd9eOPBrFDzNaoJRurs-8d37dN_nEqqjrFsoEtNy_32RC74vRo0IA
# OAuth
cas.authn.oauth.crypto.encryption.key: UfXfteRBAROe_VlXtsnBw5kIwrqAZc7SfPtnTW7llN0
cas.authn.oauth.crypto.signing.key: XJeUdyaPKz4GHNWmjlFeKlEkGlVPqFTJbOmX8ezbao9lpucrtk5IA9GX3yC6ibVe7Wa-ze4RNhD62Z2v3N8wyA
cas.authn.oauth.access-token.crypto.encryption.key: mFcyXaH00ZIIXW0dI4Djat0NH7Cdvu-2UiinjiO5SFE
cas.authn.oauth.access-token.crypto.signing.key: RfjL0ADLFzj4u5jhj6ysNk4G2P2-FIiPm04TYiENbktq-RO9zwQwsQzLg2496UlQiLNnpu1NJq7dcvsv5xDYjw
cas.authn.oauth.session-replication.cookie.crypto.encryption.key: hzB0RZ1NISOI0OFswtzUvaksvGobVHPeMllt4src0Po
cas.authn.oauth.session-replication.cookie.crypto.signing.key: q1U_Kp0qgl6uMKdVE_k4jvvE-zb3IxdtP5eIxLWbjOy74vYkfYSXspbLXR327F4D7qtuXI4DIVnvU5vEe8sH2Q
cas.authn.pac4j.core.session-replication.cookie.crypto.encryption.key: Fam8ftR1s0HgGzEyJv1r7CS48a5vER8fKPsCIB7Mv7g
cas.authn.pac4j.core.session-replication.cookie.crypto.signing.key: H9q5Z1Wog_iEzUbF021Z4d1ASDvUPHKeHekUUj4lX_Y5N57WLIyb1KxIUgtfQ6nXLoNRpejk84PDTyQO4fwXOA

# Service ticket registry
cas.authn.accept.enabled: false
cas.ticket.registry.redis.host: localhost
cas.ticket.registry.redis.port: 6379
cas.ticket.registry.redis.sentinel.master: mymaster
cas.ticket.registry.redis.sentinel.node[0]: localhost:26379
cas.ticket.registry.redis.sentinel.node[1]: localhost:26380
cas.ticket.registry.redis.sentinel.node[2]: localhost:26381

# Service registry
cas.service-registry.core.init-from-json: false
cas.service-registry.git.repository-url: https://github.com/nathancailbourdin/cas-git-service-registry-test.git
cas.service-registry.git.active-branch: main
cas.service-registry.git.branches-to-clone: main
cas.service-registry.git.clone-directory.location: file:/tmp/cas-service-registry-test
cas.service-registry.schedule.start-delay: 10000
cas.service-registry.schedule.repeat-interval: 120000
cas.service-registry.cache.duration: 900000

# LDAP
cas.authn.ldap[0].base-dn: ou=people,dc=esco-centre,dc=fr
cas.authn.ldap[0].bind-credential: admin
cas.authn.ldap[0].bind-dn: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
cas.authn.ldap[0].ldap-url: ldap://localhost:389
cas.authn.ldap[0].search-filter: (|(ENTPersonLogin={user})(ENTPersonAlias={user}))
cas.authn.ldap[0].type: AUTHENTICATED
cas.authn.ldap[0].principal-attribute-id: uid
cas.authn.ldap[0].principal-attribute-list: uid,isMemberOf,cn,sn,givenName,displayName,mail,ENTPersonLogin,ESCODomaines,ESCOUAICourant,ESCOSIRENCourant,ENTPersonProfils,ENTEleveClasses,ENTEleveNivFormation,ESCOUAI,ESCOSIREN,ESCOUAIRattachement,ENTPersonDateNaissance,ENTPersonJointure,ENTPersonStructRattach,ESCOPersonEtatCompte,ESCOPersonExternalIds

# Login Flow Interrupt
cas.interrupt.core.force-execution: true
cas.interrupt.core.trigger-mode: AFTER_SSO

# SAML
cas.authn.saml-idp.core.entity-id: https://localhost:8443/cas/idp/metadata

# Custom Properties

# Interrupt
cas.custom.properties.interrupt.structs-base-api-url: http://localhost:7001
cas.custom.properties.interrupt.structs-api-path: /structsinfo/
cas.custom.properties.interrupt.replace-domain-regex: (\?service=http:\/\/)[^\/]+(\/)

# Externalid
cas.custom.properties.externalid.base-api-url: http://localhost:7002/externalid/api
cas.custom.properties.externalid.api-path: /generateExternalId
cas.custom.properties.externalid.attribute-name-response: externalId
cas.custom.properties.externalid.attribute-name-ldap: ESCOPersonExternalIds
cas.custom.properties.externalid.split-character: $