# Ce fichier contient les properties utilisées par le serveur de délégation utilisé pour les tests avec puppeteer

# Server
server.port: 9443
spring.main.lazy-initialization: false
cas.server.name: https://localhost:9443
cas.server.prefix: https://localhost:9443/cas
cas.server.scope: cas-ci.git

# Service ticket registry
cas.authn.accept.enabled: false
cas.ticket.registry.redis.host: localhost
cas.ticket.registry.redis.port: 6379
cas.ticket.registry.redis.sentinel.master: mymaster
cas.ticket.registry.redis.sentinel.node[0]: localhost:26379
cas.ticket.registry.redis.sentinel.node[1]: localhost:26380
cas.ticket.registry.redis.sentinel.node[2]: localhost:26381
cas.ticket.registry.redis.password: OZwtXSpJCjZEQ5b
cas.ticket.registry.redis.sentinel.password: GWMije5VNMe7avz

# Service registry
cas.service-registry.core.init-from-json: false
cas.service-registry.core.init-default-services: false
cas.service-registry.json.location: classpath:/services-deleg
cas.service-registry.schedule.start-delay: 10000
cas.service-registry.schedule.repeat-interval: 120000
cas.service-registry.cache.duration: 900000

# LDAP auth
cas.authn.ldap[0].base-dn: ou=people,dc=esco-centre,dc=fr
cas.authn.ldap[0].bind-credential: admin
cas.authn.ldap[0].bind-dn: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
cas.authn.ldap[0].ldap-url: ldap://localhost:389
cas.authn.ldap[0].search-filter: (|(ENTPersonLogin={user})(ENTPersonAlias={user}))
cas.authn.ldap[0].type: AUTHENTICATED
cas.authn.ldap[0].principal-attribute-id: uid
# LDAP attribute repository
cas.person-directory.active-attribute-repository-ids: ldap
cas.person-directory.use-existing-principal-id: true
cas.authn.attribute-repository.ldap[0].id: ldap
cas.authn.attribute-repository.ldap[0].base-dn: ou=people,dc=esco-centre,dc=fr
cas.authn.attribute-repository.ldap[0].bind-credential: admin
cas.authn.attribute-repository.ldap[0].bind-dn: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
cas.authn.attribute-repository.ldap[0].ldap-url: ldap://localhost:389
cas.authn.attribute-repository.ldap[0].search-filter: uid={0}
cas.authn.attribute-repository.ldap[0].attributes.uid: uid
cas.authn.attribute-repository.ldap[0].attributes.cn: cn
cas.authn.attribute-repository.ldap[0].attributes.sn: sn
cas.authn.attribute-repository.ldap[0].attributes.mail: mail
cas.authn.attribute-repository.ldap[0].attributes.ESCOUAICourant: ESCOUAICourant
cas.authn.attribute-repository.ldap[0].attributes.givenName: givenName
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonFonctions: ENTPersonFonctions
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonProfils: ENTPersonProfils
cas.authn.attribute-repository.ldap[0].attributes.ESCOPersonProfils: ESCOPersonProfils
cas.authn.attribute-repository.ldap[0].attributes.ESCOUAI: ESCOUAI
cas.authn.attribute-repository.ldap[0].attributes.ESCOSIRENCourant: ESCOSIRENCourant
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonGARIdentifiant: ENTPersonGARIdentifiant
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonJointure: ENTPersonJointure
cas.authn.attribute-repository.ldap[0].attributes.isMemberOf: isMemberOf
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonLogin: ENTPersonLogin
cas.authn.attribute-repository.ldap[0].attributes.ESCOPersonExternalIds: ESCOPersonExternalIds

# Login Flow Interrupt
cas.interrupt.core.force-execution: false
cas.interrupt.core.trigger-mode: AFTER_SSO

# SAML
cas.authn.saml-idp.core.entity-id: https://localhost:9443/cas/idp/metadata
cas.authn.saml-idp.metadata.file-system.location: file:/etc/cas/metadata-deleg

# OIDC
cas.authn.oidc.core.issuer: https://localhost:9443/cas/oidc
cas.authn.oidc.jwks.file-system.jwks-file: /tmp/oidc/keystore.jwks
cas.authn.oidc.core.claims-map.nickname: ENTPersonLogin
cas.authn.oidc.core.claims-map.given_name: givenName
cas.authn.oidc.core.claims-map.email: mail
cas.authn.oidc.core.claims-map.family_name: sn
cas.authn.oidc.core.claims-map.usual_name: sn
cas.authn.oidc.core.claims-map.name: displayName
cas.authn.oidc.core.user-defined-scopes.test: uid,isMemberOf,usual_name
cas.authn.oidc.discovery.scopes: openid,profile,test
cas.authn.oidc.discovery.claims: sub,name,nickname,usual_name,uid,isMemberOf,email,given_name,family_name
cas.authn.oidc.id-token.include-id-token-claims: false

# MFA Redis
cas.authn.mfa.gauth.redis.sentinel.master: mymaster
cas.authn.mfa.gauth.redis.sentinel.node[0]: localhost:26379
cas.authn.mfa.gauth.redis.sentinel.node[1]: localhost:26380
cas.authn.mfa.gauth.redis.sentinel.node[2]: localhost:26381
cas.authn.mfa.gauth.redis.sentinel.password: GWMije5VNMe7avz
cas.authn.mfa.gauth.redis.password: OZwtXSpJCjZEQ5b
cas.authn.mfa.trusted.redis.sentinel.master: mymaster
cas.authn.mfa.trusted.redis.sentinel.node[0]: localhost:26379
cas.authn.mfa.trusted.redis.sentinel.node[1]: localhost:26380
cas.authn.mfa.trusted.redis.sentinel.node[2]: localhost:26381
cas.authn.mfa.trusted.redis.sentinel.password: GWMije5VNMe7avz
cas.authn.mfa.trusted.redis.password: OZwtXSpJCjZEQ5b

# Attribute definition
cas.authn.attribute-repository.attribute-definition-store.json.location: classpath:attribute-definition-deleg.json

# Crypto
cas.tgc.crypto.signing.key: W5lfIvRZKzr-vY1C4TAFUPXyBd6PteelKtUA_KlD_gJIUs312PyI8bB5qj-LOm6Tjc0O3nWNruTsxQPAyn-WWA
cas.tgc.crypto.encryption.key: 0c7NHTXuLesnQF1NlaQDJ-QxQ4vxF4NUtTF2YKUZdh9DAAufXN2BlAU3Nig5f08yG8uWn_9FF10xQ054ZQecnQ
cas.authn.oauth.crypto.signing.key: z7acHfkKoUad3Uef3xBABdVSXha5aUmtlXS4oQkci2B3OWhuSfOfs1RAuGL7eJ0ZeokPfXWZBrVqQaeRr2JDCw
cas.authn.oauth.crypto.encryption.key: uecrFRK3CKyTv2h4Z2fiAJ6XKZnsI-7ruLC6zRIyYSpRdRfSpjSNmXU4LIENIDlTvdxW8jKmpaQLTjnas2e1Tg
cas.interrupt.cookie.crypto.signing.key: 6aYk01fhZj7eJ969yXAvRl86JayHkJJR3wcmJACWoN62br-jceZqBXc8lhKAF0ul_QxP51EODwcMwTNnd8yO2A
cas.interrupt.cookie.crypto.encryption.key: sg_hRT8xK-HlnfBYxlYCCkP1v6G6QST6f1W574SZCH-tAfTr1d-Zwui6d0lxOkBtmRagyuOhg1wgZ3v6zFTvwA
cas.authn.oauth.access-token.crypto.encryption.key: ahhqKT4C5-oaKYDwzr0Sko-lUTDTLGQc1TH3KrRqiWmkYOvZLRqtbpdFY-LDwKsqV8as9cYmRrmJHwjGvT_Rxw
cas.authn.oauth.access-token.crypto.signing.key: RCJVoSWt7fe6RrX_Q18MXXJKCtWUeYj_1trOg4I_4KzIvi8JhHolTe3LQK4Dhhr-2eVHJFlqWD79lMsvDQl44g
cas.webflow.crypto.signing.key: ryNitDqGwJ_Sk7-RZ1UT1V17nVdV9pemr8BilGjqAvmENX05d1BUGCe4Cv4GDLlHP-fm4ZEIe7PcGM7Cs3nqmg
cas.webflow.crypto.encryption.key: ohRAyvDRh_QrTnmBScD8UA
cas.authn.pac4j.core.session-replication.cookie.crypto.signing.key: zVpm0QvVAGixeUAJS8euRsefSSvb19bB1b7eppcfuUZy1JXDL8v2PcnqsHlhT23_5L6ffv82ART2umCS0arZJw
cas.authn.pac4j.core.session-replication.cookie.crypto.encryption.key: HZ0gAivZQTlnWucW9L5YoqFVJtq7GdL4hZjUxS33jfhiK2j9_jJaTE6CnMC8ApMUwbNPUKGUixOoGHkgXEfKlA
cas.authn.oauth.session-replication.cookie.crypto.signing.key: 3ykjQEehmU-V_zvJgXqBcXjRiVEVDtoalFoDzt3mDoZwg9oCDUCmGiMukLaRcK2Kl5aOdbS-vyucR4Zssh5bCA
cas.authn.oauth.session-replication.cookie.crypto.encryption.key: b2m08Llbt9kBR7fStlUdOO2L1OVxZ5XafObZlHljUtAfgoyBa5zUKBdPWo7u6UP2cbZyg7udvw55SZc3s3jvHA
