# Ce fichier contient les properties utilisées par le serveur de délégation utilisé pour les tests avec puppeteer

# Server
server.port: 9443
spring.main.lazy-initialization: false
cas.server.name: https://localhost:9443
cas.server.prefix: https://localhost:9443/cas
cas.server.scope: cas-ci.git

# Monitoring endpoints
# Health
management.endpoints.web.exposure.include: health,prometheus           
management.endpoint.health.enabled: true
management.health.redis.enabled: true
management.endpoint.health.show-details: always
cas.monitor.endpoints.endpoint.health.access: ANONYMOUS

# Service ticket registry
cas.authn.accept.enabled: false
cas.ticket.registry.redis.host: localhost
cas.ticket.registry.redis.port: 6379
cas.ticket.registry.redis.sentinel.master: mymaster
cas.ticket.registry.redis.sentinel.node[0]: localhost:26379
cas.ticket.registry.redis.sentinel.node[1]: localhost:26380
cas.ticket.registry.redis.sentinel.node[2]: localhost:26381
cas.ticket.registry.redis.password: OZwtXSpJCjZEQ5b
cas.ticket.registry.redis.sentinel.password: GWMije5VNMe7avz

# Service registry
cas.service-registry.core.init-from-json: false
cas.service-registry.core.init-default-services: false
cas.service-registry.json.location: classpath:/services-deleg
cas.service-registry.schedule.start-delay: 10000
cas.service-registry.schedule.repeat-interval: 120000
cas.service-registry.cache.duration: 900000

# LDAP auth
cas.authn.ldap[0].base-dn: ou=people,dc=esco-centre,dc=fr
cas.authn.ldap[0].bind-credential: admin
cas.authn.ldap[0].bind-dn: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
cas.authn.ldap[0].ldap-url: ldap://localhost:389
cas.authn.ldap[0].search-filter: (|(ENTPersonLogin={user})(ENTPersonAlias={user}))
cas.authn.ldap[0].type: AUTHENTICATED
cas.authn.ldap[0].principal-attribute-id: uid
# LDAP attribute repository
cas.person-directory.active-attribute-repository-ids: ldap
cas.person-directory.use-existing-principal-id: true
cas.authn.attribute-repository.ldap[0].id: ldap
cas.authn.attribute-repository.ldap[0].base-dn: ou=people,dc=esco-centre,dc=fr
cas.authn.attribute-repository.ldap[0].bind-credential: admin
cas.authn.attribute-repository.ldap[0].bind-dn: cn=admin,ou=administrateurs,dc=esco-centre,dc=fr
cas.authn.attribute-repository.ldap[0].ldap-url: ldap://localhost:389
cas.authn.attribute-repository.ldap[0].search-filter: uid={0}
cas.authn.attribute-repository.ldap[0].attributes.uid: uid
cas.authn.attribute-repository.ldap[0].attributes.cn: cn
cas.authn.attribute-repository.ldap[0].attributes.sn: sn
cas.authn.attribute-repository.ldap[0].attributes.mail: mail
cas.authn.attribute-repository.ldap[0].attributes.ESCOUAICourant: ESCOUAICourant
cas.authn.attribute-repository.ldap[0].attributes.givenName: givenName
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonFonctions: ENTPersonFonctions
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonProfils: ENTPersonProfils
cas.authn.attribute-repository.ldap[0].attributes.ESCOPersonProfils: ESCOPersonProfils
cas.authn.attribute-repository.ldap[0].attributes.ESCOUAI: ESCOUAI
cas.authn.attribute-repository.ldap[0].attributes.ESCOSIRENCourant: ESCOSIRENCourant
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonGARIdentifiant: ENTPersonGARIdentifiant
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonJointure: ENTPersonJointure
cas.authn.attribute-repository.ldap[0].attributes.isMemberOf: isMemberOf
cas.authn.attribute-repository.ldap[0].attributes.ENTPersonLogin: ENTPersonLogin
cas.authn.attribute-repository.ldap[0].attributes.ESCOPersonExternalIds: ESCOPersonExternalIds

# Login Flow Interrupt
cas.interrupt.core.force-execution: true
cas.interrupt.core.trigger-mode: AFTER_SSO

# SAML
cas.authn.saml-idp.core.entity-id: https://localhost:9443/cas/idp/metadata

# OIDC
cas.authn.oidc.core.issuer: https://localhost:9443/cas/oidc
cas.authn.oidc.jwks.file-system.jwks-file: /tmp/oidc/keystore.jwks
cas.authn.oidc.core.claims-map.nickname: ENTPersonLogin
cas.authn.oidc.core.claims-map.given_name: givenName
cas.authn.oidc.core.claims-map.email: mail
cas.authn.oidc.core.claims-map.family_name: sn
cas.authn.oidc.core.claims-map.usual_name: sn
cas.authn.oidc.core.claims-map.name: displayName
cas.authn.oidc.core.user-defined-scopes.test: uid,isMemberOf,usual_name
cas.authn.oidc.discovery.scopes: openid,profile,test
cas.authn.oidc.discovery.claims: sub,name,nickname,usual_name,uid,isMemberOf,email,given_name,family_name
cas.authn.oidc.id-token.include-id-token-claims: false

# Attribute definition
cas.authn.attribute-repository.attribute-definition-store.json.location: classpath:attribute-definition-deleg.json