# Ce fichier contient les properties utilisées pour les tests avec puppeteer
cas.server.name: https://localhost:8443
cas.server.prefix: https://localhost:8443/cas
server.port: 8443
spring.main.lazy-initialization: false
management.endpoints.web.discovery.enabled: true
cas.audit.engine.enabled: true
cas.audit.slf4j.use-single-line: true
cas.monitor.endpoints.endpoint.defaults.access: ANONYMOUS
management.health.redis.enabled: true
management.health.redisHealthIndicator.enabled: true
management.endpoints.web.exposure.include: health,ssoSessions,ticketRegistry
management.endpoint.health.show-details: always
management.endpoints.enabled-by-default: true
cas.service-registry.redis.host: localhost
cas.service-registry.redis.port: 6379
cas.ticket.registry.redis.host: cas2
cas.ticket.registry.redis.port: 6379
cas.audit.redis.host: cas2
cas.audit.redis.port: 6379
cas.service-registry.core.init-from-json: false
cas.service-registry.git.repository-url: https://github.com/nathancailbourdin/cas-git-service-registry-test.git
cas.service-registry.git.active-branch: main
cas.service-registry.git.branches-to-clone: main
cas.service-registry.git.clone-directory.location: file:/tmp/cas-service-registry-test
cas.service-registry.schedule.start-delay: 10000
cas.service-registry.schedule.repeat-interval: 120000
cas.service-registry.cache.duration: 900000