name: CAS Custom Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/iron'

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Create keystore
      run: |
        chmod +x ./gradlew
        sudo chown $USER:$USER /etc
        ./gradlew createKeystore
        cp /etc/cas/cas.crt /etc/cas/cas.pem
        sudo keytool -importcert -trustcacerts -file /etc/cas/cas.pem -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -alias cas -noprompt
        sudo apt-get update
        sudo apt install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl pkg-config
        pip install --no-binary lxml==5.2.1 lxml==5.2.1 --force-reinstall
        pip install --no-binary xmlsec==1.3.14 xmlsec==1.3.14
        pip install --no-binary signxml==3.2.2 signxml==3.2.2

    - name: Disable IPv6
      run: |
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1

    - name: Run Pupeteer scenarios
      run: |
        mkdir /etc/cas/metadata-deleg
        chmod +x puppeteer/run.sh
        CAS_ARGS="-Dcom.sun.net.ssl.checkRevocation=false --spring.profiles.active=test" CAS_DELEG_ARGS="-Dcom.sun.net.ssl.checkRevocation=false --spring.profiles.active=deleg" SCENARIO_FOLDER="scenarios" ./puppeteer/run.sh