name: CAS Custom Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/iron'

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Create keystore
      run: |
        chmod +x ./gradlew
        sudo chown $USER:$USER /etc
        ./gradlew createKeystore

    - name: Disable IPv6
      run: |
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1

    - name: Run Pupeteer scenarios
      run: |
        chmod +x puppeteer/run.sh
        CAS_ARGS="-Dcom.sun.net.ssl.checkRevocation=false --spring.profiles.active=test" CAS_DELEG_ARGS="--spring.profiles.active=deleg" ./puppeteer/run.sh